---
- name: "cron_jobs | Deploy cron daemon settings"
  ansible.builtin.template:
    src: "crond.j2"
    dest: "/etc/sysconfig/crond"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  when:
    - "vars['cron_jobs_settings'] is defined"
    - "vars['cron_jobs_settings'] != ''"
    - "vars['cron_jobs_settings'] != []"
    - "hostvars[inventory_hostname]['ansible_os_family'] in ['RedHat',
      'Archlinux']"
  notify:
    - "Restart crond"
- name: "cron_jobs | Enable cron daemon"
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['cron_jobs_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['cron_jobs'] is defined"
    - "hostvars[inventory_hostname]['cron_jobs'] != ''"
    - "hostvars[inventory_hostname]['cron_jobs'] |
       community.general.json_query(vars['cron_jobs_enable']) is defined"
    - "hostvars[inventory_hostname]['cron_jobs'] |
       community.general.json_query(vars['cron_jobs_enable']) == 'true'"
  vars:
    cron_jobs_enable: "[] | map(&enable || 'false', @) | [0]"
