---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['cron_jobs'] is defined"
    - "hostvars[inventory_hostname]['cron_jobs'] != ''"
    - "hostvars[inventory_hostname]['cron_jobs'] |
       community.general.json_query(vars['cron_jobs_install_package']) is
       defined"
    - "hostvars[inventory_hostname]['cron_jobs'] |
       community.general.json_query(vars['cron_jobs_install_package']) ==
       'true'"
  vars:
    cron_jobs_install_package: "[] | map(&install_package || 'false', @) | [0]"
- ansible.builtin.include_tasks:
    file: "deploy.yml"
  when:
    - "vars['cron_jobs_settings'] is defined"
    - "vars['cron_jobs_settings'] != ''"
