---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "hostvars[inventory_hostname]['cron_jobs_install_package'] is defined"
  - "hostvars[inventory_hostname]['cron_jobs_install_package'] == 'true'"
- include: deploy_cron_jobs.yml
  when:
  - "hostvars[inventory_hostname]['cron_jobs'] is defined"
  - "hostvars[inventory_hostname]['cron_jobs'] != ''"
