---
- import_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['cron_jobs_install_package'] is defined"
  - "hostvars[inventory_hostname]['cron_jobs_install_package'] == 'true'"
- include_tasks: deploy_cron_jobs.yml
  when:
  - "hostvars[inventory_hostname]['cron_jobs'] is defined"
  - "hostvars[inventory_hostname]['cron_jobs'] != ''"
