---
- name: Restart cron
  service:
    name: "{{ hostvars[inventory_hostname]['cron_jobs_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['cron_jobs_restart'] is defined"
  - "hostvars[inventory_hostname]['cron_jobs_restart'] == 'true'"
